### ISSUE TITLE
NodeJS

### ISSUE THREAD

**Issue by mpetuska** [sdkman/sdkman-vendor-gradle-plugin#14]
Hello,

I keep missing NodeJS in SDKMAN and as such am forced to download a separate tool just for that (nvm). I am in no way affiliated or related to nodejs project team, however I'd be happy to maintain and publish nodejs releases to sdkman. 

My main concern is if that's ok with you guys (licencing and stuff...). If so, all I need are just sdkman credentials to publish updates under.

**Comment by marc0der** [comment]
Hi @mpetuska, please feel free to chat to us on slack about this. I'm closing this issue as it has nothing to do with the grade plugin.
