### ISSUE TITLE
Vendor keys for ktx

### ISSUE THREAD

**Issue by mpetuska** [sdkman/sdkman-vendor-gradle-plugin#16]
Hi, I'm currently working on [mpetuska/ktx](https://github.com/mpetuska/ktx) to bring npx capabilities to kotlin scripting ecosystem. The project is nearing first dev preview release and I'm wondering if now would be a good time to integrate with sdkman to avoid wasting time on selfinstall scripts. If so, I'd need a set of vendor secrets, please.

**Comment by mpetuska** [comment]
Additionally I'd like some guidance on how to package qn artefact for sdkman platform and gow to specify which paths should be appended.

**Comment by marc0der** [comment]
Hi @mpetuska, you are welcome to follow the process outlined [here](https://github.com/sdkman/sdkman-cli/wiki/Vendor-onboarding-process).

**Comment by mpetuska** [comment]
Hi, the linked page outlines obtaining vendor keys perfectly, thanks. Do you have similar documentation on what is the "well formed sdk archive" mentioned there?

**Comment by helpermethod** [comment]
Hi @mpetuska, 

well formed SDK archive basically means:

* a ZIP or TAR file
* with a top-level directory and a `bin` directory underneath, sth like

```
ktx-0.1.0/ <-- the top level directory
    |
    -- bin/
       |
       `-- ktx <-- ktx binary or shell script
    README.md <-- optional
    License.txt <-- optional
```

Sorry I'm on my phone, so limited drawing capabilities 😁.

**Comment by mpetuska** [comment]
The drawing is awesome! That looks like what gradle's application plugin spits out in `distZip`. So far so good, but ktx relies on adding a particular directory to user's PATH to work. Is there any way to tell sdkman to do so?

**Comment by marc0der** [comment]
SDKMAN will add the bin folder of the currently selected version to the PATH automatically. We don't provide a way to add other custom directories to the path, so your users would need to do it themselves.

**Comment by marc0der** [comment]
So after this, I've finally done it! I've written a [wiki page](https://github.com/sdkman/sdkman-cli/wiki/Well-formed-SDK-archives) that describes what a well-formed archive is. I hope this helps you and any fellow travellers in the future @mpetuska :smile: 

Please don't hesitate to contact us on our [community slack](https://slack.sdkman.io/) `#vendors` channel if you have any questions about onboarding your candidate.
