### ISSUE TITLE
Apache TinkerPop support

### ISSUE THREAD

**Issue by bkmeneguello** [sdkman/sdkman-vendor-gradle-plugin#6]
I'm not from Apache TinkerPop team, so, it's possible to add them to vendors?

**Comment by marc0der** [comment]
The project that you should be looking at to add new Candidates and versions is the [database migration](https://github.com/sdkman/sdkman-db-migrations) project. You can follow our normal [contributor guidelines](https://github.com/sdkman/sdkman-cli/blob/master/CONTRIBUTING.md) prior to raising a PR.
